# ???????
spring.datasource.url=jdbc:h2:file:./data/shopdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=SA
spring.datasource.password=

# H2 ?????
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# ?? H2 Console ??????????????? Frame ??
spring.h2.console.settings.web-allow-others=true

# JPA/Hibernate ??
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# JSP ??????? (???????? Controller ????? JSP)
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

# Enable Multipart implementation
spring.servlet.multipart.enabled=true
# Threshold after which files are written to disk.
spring.servlet.multipart.file-size-threshold=2MB
# Max file size
spring.servlet.multipart.max-file-size=500MB
# Max request size
spring.servlet.multipart.max-request-size=1GB


upload.path=uploads/